/** Writes the relay's linked script into the host kit as a Scala string, so the JVM (which serves it) and the browser
  * (which writes it into a `srcdoc`) carry the same bytes. A JVM string constant holds at most 65535 bytes, so the
  * script goes in as many literals, each short enough even when every character is escaped.
  */
object RelayScriptGen:
  def source(script: String): String =
    val parts = script.grouped(8192).map(literal).mkString(",\n    ")
    s"""package heddle.mcp.apps.host
       |
       |/** The relay's linked script (`heddle-mcp-apps-relay`), generated by the build. Do not edit. */
       |private[host] object RelayScript:
       |  val text: String = List(
       |    $parts
       |  ).mkString
       |""".stripMargin

  private def literal(s: String): String =
    val b = new StringBuilder("\"")
    s.foreach {
      case '"'                     => b ++= "\\\""
      case '\\'                    => b ++= "\\\\"
      case '\n'                    => b ++= "\\n"
      case '\r'                    => b ++= "\\r"
      case '\t'                    => b ++= "\\t"
      case c if c < ' ' || c > '~' => b ++= f"\\u${c.toInt}%04x"
      case c                       => b += c
    }
    b += '"'
    b.result()
end RelayScriptGen
