import java.nio.charset.StandardCharsets
import java.security.MessageDigest
import java.util.Base64

/** Writes the relay's linked script into the host kit as a Scala string, so the JVM (which serves it) and the browser
  * (which writes it into a `srcdoc`) carry the same bytes, and writes its CSP hash beside it, so no host hashes
  * megabytes at run time. A JVM string constant holds at most 65535 bytes, so the script goes in as many literals, each
  * short enough even when every character is escaped.
  */
object RelayScriptGen:
  def source(linked: String): String =
    // `</script` inside the bundle would end the element early; `<\/script` means the same to JavaScript.
    val script = linked.replace("</script", "<\\/script")
    val digest = MessageDigest.getInstance("SHA-256").digest(script.getBytes(StandardCharsets.UTF_8))
    val hash   = "sha256-" + Base64.getEncoder.encodeToString(digest)
    val parts  = script.grouped(8192).map(literal).mkString(",\n    ")
    s"""package heddle.mcp.apps.host
       |
       |import heddle.mcp.apps.ScriptHash
       |
       |/** The relay's linked script (`heddle-mcp-apps-relay`) and its CSP hash, generated by the build. Do not edit. */
       |private[host] object RelayScript:
       |  val hash: ScriptHash = ScriptHash("$hash")
       |
       |  val text: String = List(
       |    $parts
       |  ).mkString
       |""".stripMargin

  private def literal(s: String): String =
    val b = new StringBuilder("\"")
    s.foreach {
      case '"'                     => b ++= "\\\""
      case '\\'                    => b ++= "\\\\"
      case '\n'                    => b ++= "\\n"
      case '\r'                    => b ++= "\\r"
      case '\t'                    => b ++= "\\t"
      case c if c < ' ' || c > '~' => b ++= f"\\u${c.toInt}%04x"
      case c                       => b += c
    }
    b += '"'
    b.result()
end RelayScriptGen
